name: deploy to prd-xserver

on: 
    push:
      tags:
        - 'stg.v.*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dokcer-compose up
        run: |
          docker compose up -d
      - name: npm run install
        run: |
          docker compose exec app npm install
      - name: npm build
        run: |
          docker compose exec app npm run build
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.STG_FTP_SERVER }}
          username: ${{ secrets.STG_FTP_USERNAME }}
          password: ${{ secrets.STG_FTP_PASSWORD }}
          local-dir: ./src/
          server-dir: ./
          exclude: |
            **/node_modules/**
            **/resources/js/**
            **/vendor/**
            .env
            tests/**
            storage/**
            *.log
            *.cache